### ISSUE TITLE
support for using rpl with this? 

### ISSUE THREAD

**Issue by pokeball99** [M4GNV5/CommandBlocksJS#6]
http://tossha.com/rpl/

**Comment by WebFreak001** [comment]
first rpl is pretty much crap because its just a preprocessor and not a real programming language and also you can do everything you can do with that in JavaScript/TypeScript with CommandBlocksJS

**Comment by pokeball99** [comment]
well it would be just for some of them like this:
tpsmart @Sheep x vx 20 400 10 0.02 0.4
which when exucuted makes this:
tp @e[type=Sheep,score_vx_min=20,score_vx=29] ~0.02 ~ ~
tp @e[type=Sheep,score_vx_min=30,score_vx=39] ~0.03 ~ ~
tp @e[type=Sheep,score_vx_min=40,score_vx=49] ~0.041 ~ ~
... and so on untill:
tp @e[type=Sheep,score_vx_min=380,score_vx=389] ~0.39 ~ ~
tp @e[type=Sheep,score_vx_min=390,score_vx=400] ~0.4 ~ ~

**Comment by WebFreak001** [comment]
Instead this works too:

``` typescript
function tpsmart(selector: Selector, score: string, minScore: number, maxScore: number, min: number, max: number, axis: Vector3, step: number, speed: number)
{
    for(var i = minScore; i <= maxScore; i += step)
    {
        selector.setAttribute("score_" + score + "_min", "" + i);
        selector.setAttribute("score_" + score, "" + (i + step - 1));
        var t = (i - minScore) / maxScore;
        command("tp " + selector.toString() + " ~" + (min + axis.x * t * (max - min)) + " ~" + (min + axis.y * t * (max - min)) + " ~" + (min + axis.z * t * (max - min)));
    }
}
```
(code is not tested, please validate)

**Comment by WebFreak001** [comment]
But instead we could implement everything they support if that fits your needs

**Comment by pokeball99** [comment]
that would work wonderfully

**Comment by M4GNV5** [comment]
Ok to conclude this as far as i can see rpl has "only" three functions. They actually all seems very useless to me too...
* sqrt and sin just spawn a bunch of entities whats even worse as its affects the performance of your computer. Anyways I was planning to implement mathematic functions like sqrt, sin, cos etc. a more mathematical way so stay tuned for this update :wink: 
* tpsmart just creates a bunch of commandblocks, so if you really want to have this its very easy to create using CommandblocksJS (see @WebFreak001 's answer) or you might better create an endless loop that tps ppl according to their current score and then removes 1 or more from this score e.g.:
```javascript
var scoreTpObjective = new Scoreboard.Objective(Scoreboard.ObjectiveType.dummy, "tpObj");
function scoreTp()
{
    var sel = new Entities.Selector();
    var argMin = Entities.SelectorArgument.scoreMin(scoreTpObjective);
    var argMax = Entities.SelectorArgument.scoreMax(scoreTpObjective);
    for(var i = 1; i < 101; i *= 10)
    {
        argMin.setValue(i);
        argMax.setValue(i);
        sel.setArgument(argMin);
        sel.setArgument(argMax);
        command("tp " + sel.toString() + " ~" + i + " ~ ~");
        scoreTpObjective.remove(sel, i);
    }
    call(scoreTp);
}
call(scoreTp);
```
this will teleport a player that has e.g. a score of 142 one time by 100, 4 times by 10 and 2 times by 1 coordinates towards the x axis with only ~10 commandblocks
